# Generated by Django 4.2.7 on 2024-03-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateint',
            name='image',
            field=models.ImageField(upload_to='patient/images'),
        ),
    ]
